extends: ../../../gki/gki-5.10.yml

device:
  name: marble
  platform: qcom
  soc: sm7475

kernel_source: xiaomi/sm8450
devicetrees: xiaomi/sm8450-devicetrees

kernel:
  defconfig:
    base: gki_defconfig
    fragments:
      - arch/arm64/configs/vendor/waipio_GKI.config
      - arch/arm64/configs/vendor/xiaomi_GKI.config
      - arch/arm64/configs/vendor/marble_GKI.config
      - arch/arm64/configs/vendor/addon.config
      - arch/arm64/configs/vendor/debugfs.config
    custom: []
  config_overrides:
    CONFIG_LOCALVERSION: '"-marble"'

toolchain:
  clang: ""
  profile: performance
  profiles:
    performance:
      extra_cflags:
        - "-O3"
        - "-march=armv8.2-a"
      kbuild_ldflags: []

ext_modules:
  root: kernel/xiaomi/sm8450-modules
  sources:
    - qcom/opensource/mmrm-driver
    - qcom/opensource/audio-kernel
    - qcom/opensource/camera-kernel
    - qcom/opensource/cvp-kernel
    - qcom/opensource/dataipa/drivers/platform/msm
    - qcom/opensource/datarmnet/core
    - qcom/opensource/datarmnet-ext/aps
    - qcom/opensource/datarmnet-ext/offload
    - qcom/opensource/datarmnet-ext/shs
    - qcom/opensource/datarmnet-ext/perf
    - qcom/opensource/datarmnet-ext/perf_tether
    - qcom/opensource/datarmnet-ext/sch
    - qcom/opensource/datarmnet-ext/wlan
    - qcom/opensource/display-drivers/msm
    - qcom/opensource/eva-kernel
    - qcom/opensource/video-driver
    - qcom/opensource/wlan/qcacld-3.0/.qca6490
    - qcom/opensource/wlan/qcacld-3.0/.qca6750

dtb:
  wildcard: "sm7475*.dtb"
  dtbo_wildcard: "sm7475*-overlay.dtbo"
  techpack_dirs: []

modules:
  first_stage: kernel/xiaomi/sm8450/modules.list.msm.waipio
  second_stage: device/xiaomi/sm8450-common/modules.list.second_stage
  vendor_dlkm: device/xiaomi/sm8450-common/modules.list.vendor_dlkm

output:
  dist: out/dist/marble
  zip: "AnyKernel3-marble-{version}.zip"
